name: Build the repo
on: push
jobs:
        build:
                name: Build packages
                runs-on: ubuntu-20.04
                steps:
                        - uses: actions/checkout@v2
                        - name: Change directory
                          run: cd $GITHUB_WORKSPACE
                        - name: Pull base image
                          run: docker pull archlinux:latest
                        - name: Create build image
                          run: docker build --no-cache -t builder:latest .
                        - name: Build packages
                          id: build_packages
                          run: docker run --rm -v $(pwd)/output:/build/output builder:latest
                        - name: Upload repo
                          uses: actions/upload-artifact@v2
                          with:
                                  name: repo
                                  asset_path: ./output/
